backend:
  name: gatsby-howrse
  branch: master # Branch to update (optional; defaults to master)

load_config_file: false
media_folder: static/assets
public_folder: /assets

collections:
  - name: "coats" # Used in routes, e.g., /admin/collections/blog
    label: "Golden Apple" # Used in the UI
    folder: "_content/coats" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Notes", name: "notes", widget: "text" }
      - { label: "Limited?", name: "limited", widget: "bootlean" }
      - { label: "User Number", name: "use", widget: "number" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["purple"] }
  - name: "divines" # Used in routes, e.g., /admin/collections/blog
    label: "Divines" # Used in the UI
    folder: "_content/divines" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Notes", name: "notes", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["purple"] }
  - name: "page-info"
    label: "page-info"
    folder: "_content/text"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown }
