backend:
  name: github
  ## Set to false to prevent transforming images in media gallery view
  repo: jennego/gatsby-howrse
  branch: master # Branch to update (optional; defaults to master)

media_library:
  name: cloudinary
  config:
    cloud_name: purplepony
    api_key: 351636599549869

public_folder: /assets
media_folder: /static/assets

collections:
  - name: "coats" # Used in routes, e.g., /admin/collections/blog
    label: "Golden Apple" # Used in the UI
    folder: "content/coats" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Notes", name: "notes", widget: "text", required: false }
      - {
          label: "Limited?",
          name: "limited",
          widget: "boolean",
          default: false,
        }
      - { label: "Use Number", name: "use", widget: "number", required: false }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          [
            "red",
            "orange",
            "yellow",
            "green",
            "blue",
            "unicorn",
            "pegasus",
            "riding horse",
            "pony",
            "draft",
            "donkey",
            "sea",
            "space",
          ]
        default: "purple"
  - name: "divines" # Used in routes, e.g., /admin/collections/blog
    label: "Divines" # Used in the UI
    folder: "content/divines" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Notes", name: "notes", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
      - label: "Coats Page"
        name: "coats"
        file: "site/content/coats.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
      - label: "Divine Page"
        name: "divines"
        file: "site/content/divines.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
      - label: "Home Text"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Section1, name: section1, widget: markdown }
